2 Schedule batch view
Semesterproject4/front-end pull request #11
Opened 2021-05-14 23:48 UTC by Kaszz

Closes #2 

## Description
Added the view for scheduled batches. It consists of a form for adding batches, and a list of added batches, which live in each their component.
It is possible to add view and remove scheduled batches.

The layout and proof of it working can be seen in the following gif. Additionally the button will be disabled if the speed contains non-number characters or is greater than the maximum speed allowed for the product type.
![](https://s3.gifyu.com/images/example956ac2d9f202ea99.gif)

2021-05-16 13:36 UTC, Wylardt approved these changes

2021-05-17 06:18 UTC, Teyson approved these changes

2021-05-17 06:43 UTC, Lawst96 approved these changes
Might want to add some outline to the elements in the scheduling form. It's kinda hard to see where "amount" ends and "speed" begins.

2021-05-17 06:43 UTC, Lawst96 commented on src/components/SchedulingForm.js
> +				<input placeholder="Amount..." value={amount} onChange={onAmountChanged}/>
```suggestion
				<input placeholder="Amount" value={amount} onChange={onAmountChanged}/>
```
Det stikker lidt ud at det er den eneste med "..."

2021-05-17 06:47 UTC, Kechr requested changes

2021-05-17 06:47 UTC, Kechr commented on src/components/SchedulingList.js
> +						<th>⏲️ Speed</th>
Don't know if I am a fan of emojis 😄

2021-05-17 06:47 UTC, Kechr commented on src/components/SchedulingList.js
> +							<td style={{textAlign: "right", width: "10px"}}><Deletebutton onClick={removeScheduledBatch}>🗑️</Deletebutton></td>
Same as the previous comment.

2021-05-17 06:47 UTC, Kechr commented on src/components/SchedulingList.js
> +	background-color: #f44336;
I think we could benefit from a more toned down red.

2021-05-17 06:47 UTC, Kechr commented on src/components/SchedulingList.js
> +					<tr>
Should we show the placement in the queue?
In case we have, let's say 20 scheduled batches, we would have to scroll some way down, and might lose track of where in the queue we are.

2021-05-17 07:34 UTC, Kechr approved these changes

2021-05-17 07:39 UTC, dottore1 approved these changes

2021-05-17 07:44 UTC, merged